optimizer: {
  type: sgd,
  skip_wd: [ ],
  weight_decay: !!float 0.967,
  kwargs: {
    lr: !!float 0.0005 ,
    momentum: !!float 0.9
  }
}

scheduler: {
  type: CosLR,
  kwargs: {
    t_initial: 250,
    cycle_limit: 1,
    lr_min: !!float 1e-4
  }
}

model: {
  ENCO_NAME: PointBERTL14,
  cla_input_dim: 768,
  dropout: !!float 0.5,
  act: gelu

}
